# Generated by Django 5.1.4 on 2025-01-03 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_remove_user_country_remove_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('bills', 'Bills'), ('entertainment', 'Entertainment'), ('groceries', 'Groceries'), ('diningout', 'Diningout'), ('transportation', 'Transportation'), ('personalCare', 'PersonalCare'), ('education', 'Education'), ('lifeStyle', 'LifeStyle'), ('shopping', 'Shopping'), ('general', 'General')], max_length=255)),
                ('theme_color', models.CharField(choices=[('#FF6B6B', 'Coral Red'), ('#4ECDC4', 'Turquoise'), ('#45B7D1', 'Sky Blue'), ('#96CEB4', 'Sage Green'), ('#FFEEAD', 'Soft Yellow'), ('#D4A5A5', 'Dusty Rose'), ('#9370DB', 'Purple'), ('#3CB371', 'Forest Green')], max_length=255)),
                ('maximum_spend', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
