# Generated by Django 5.1.4 on 2025-01-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='maximum_spend',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
