# Generated by Django 5.1.4 on 2025-01-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_budget_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='theme_color',
            field=models.CharField(choices=[('#394a51', 'Charcoal Gray'), ('#7fa99b', 'Seafoam Green'), ('#fbf2d5', 'Light Cream'), ('#fdc57b', 'Goldenrod'), ('#fad662', 'Light Yellow'), ('#e57b5c', 'Coral'), ('#be4747', 'Burgundy'), ('#ffb6b9', 'Light Pink')], max_length=255),
        ),
    ]
