# Generated by Django 5.1.4 on 2025-01-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_budget_theme_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('Bills', 'Bills'), ('Entertainment', 'Entertainment'), ('Groceries', 'Groceries'), ('Diningout', 'Diningout'), ('Transportation', 'Transportation'), ('PersonalCare', 'PersonalCare'), ('Education', 'Education'), ('LifeStyle', 'LifeStyle'), ('Shopping', 'Shopping'), ('General', 'General')], max_length=255),
        ),
    ]
