# Generated by Django 5.1.4 on 2025-01-04 22:10

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_token_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default=secrets.token_urlsafe, max_length=255, unique=True),
        ),
    ]
