# Generated by Django 5.1.4 on 2025-01-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
