# Generated by Django 5.1.4 on 2025-01-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_token_user_token_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='api_user',
        ),
    ]
