# Generated by Django 5.1.4 on 2025-01-05 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='api_user',
        ),
    ]
